server:
  port: 8081

sapci:
  tenantUrl: https://b65f2da8trial.it-cpitrial03.cfapps.ap21.hana.ondemand.com
  tokenUrl: https://b65f2da8trial.authentication.ap21.hana.ondemand.com/oauth/token
  clientId: sb-d6dbcac6-a9e3-4560-9d45-dec494c7daf2!b140547|it!b196
  clientSecret: a79542d3-5554-4326-904d-b2dc8c20214b$Y_fWgeUXxAWilnToexX_CC_-jawTWdJpv7LyFvxeM-Q=
  messageProcessingApi: https://b65f2da8trial.it-cpitrial03.cfapps.ap21.hana.ondemand.com/api/v1/MessageProcessingLogs
  runtimeUrl: https://b65f2da8trial.it-cpitrial03-rt.cfapps.ap21.hana.ondemand.com
  runtimeTokenUrl: https://b65f2da8trial.authentication.ap21.hana.ondemand.com/oauth/token
  runtimeClientId: sb-091f3e35-24a0-4d8e-93b6-8a8647e8fe4e!b140547|it-rt-b65f2da8trial!b196
  runtimeClientSecret: d5ffb1d8-b136-4153-b240-de35a163b270$jp7sKT-s8HVxx_RLvUAyBtUhadKQviMvim75aENKDZQ=
  targetReceiverUrl: https://resend-testing.free.beeceptor.com

logging:
  level:
    com.example.sapcimonitor: DEBUG
